export enum ICON_NAMES {
  checkCircle = 'check-circle',
  check = 'check',
  checkSquare = 'check-square',
  checkboxChecked = 'checkbox-checked',
  checkbox = 'checkbox',
  clipboardCopy = 'clipboard-copy',
  cloudUploadActive = 'cloud-upload-active',
  cloudUpload = 'cloud-upload',
  document = 'document',
  exclamationCircle = 'exclamation-circle',
  exclamation = 'exclamation',
  informationCircle = 'information-circle',
  metamask = 'metamask',
  note = 'note',
  wavingHand = 'waving-hand',
  xCircle = 'x-circle',
}
