export enum ICON_NAMES {
  backwardStep = 'backward-step',
  checkCircle = 'check-circle',
  check = 'check',
  checkSquare = 'check-square',
  checkboxChecked = 'checkbox-checked',
  checkbox = 'checkbox',
  chevronLeft = 'chevron-left',
  chevronRight = 'chevron-right',
  clipboardCopy = 'clipboard-copy',
  cloudUploadActive = 'cloud-upload-active',
  cloudUpload = 'cloud-upload',
  document = 'document',
  exclamationCircle = 'exclamation-circle',
  exclamation = 'exclamation',
  forwardStep = 'forward-step',
  informationCircle = 'information-circle',
  metamask = 'metamask',
  note = 'note',
  search = 'search',
  wavingHand = 'waving-hand',
  xCircle = 'x-circle',
}
