export enum ICON_NAMES {
  checkCircle = 'check-circle',
  check = 'check',
  check2 = 'check2',
  checkSquare = 'check-square',
  checkboxChecked = 'checkbox-checked',
  checkbox = 'checkbox',
  clipboardCopy = 'clipboard-copy',
  cloudUploadActive = 'cloud-upload-active',
  cloudUpload = 'cloud-upload',
  document = 'document',
  downloadCircle = 'download-circle',
  downloadCircle2 = 'download-circle2',
  download = 'download',
  exclamationCircle = 'exclamation-circle',
  exclamation = 'exclamation',
  fileCsv = 'file-csv',
  fileDoc = 'file-doc',
  fileJpg = 'file-jpg',
  filePdf = 'file-pdf',
  filePng = 'file-png',
  fileXls = 'file-xls',
  informationCircle = 'information-circle',
  metamask = 'metamask',
  note = 'note',
  wavingHand = 'waving-hand',
  xCircle = 'x-circle',
}
