/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TimestampContract } from "./TimestampContract";
export * as factories from "./factories";
export { TimestampContract__factory } from "./factories/TimestampContract__factory";
