/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  PoseidonHashContract,
  PoseidonHashContractInterface,
} from "../PoseidonHashContract";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes32[1]",
        name: "input",
        type: "bytes32[1]",
      },
    ],
    name: "poseidon",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "pure",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "uint256[1]",
        name: "input",
        type: "uint256[1]",
      },
    ],
    name: "poseidon",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "pure",
    type: "function",
  },
];

export class PoseidonHashContract__factory {
  static readonly abi = _abi;
  static createInterface(): PoseidonHashContractInterface {
    return new utils.Interface(_abi) as PoseidonHashContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PoseidonHashContract {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as PoseidonHashContract;
  }
}
